version: "3.7"

services:
  mongoDB:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build:
      context: .
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://localhost:27017/backendEngineer_development
    ports:
      - 3000:3000
    external_links:
      - mongo
    depends_on:
      - mongoDB
